name: circular_buffer
version: 0.8.0
description: >
  A Dart Circular Buffer container based on List with a fixed capacity.
homepage: https://www.github.com/kranfix/dart-circularbuffer
documentation: https://www.github.com/kranfix/dart-circularbuffer#readme
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  very_good_analysis: ^2.0.0
  test: ^1.16.4
