name: circular_buffer
version: 0.7.1
description: A Dart Circular Buffer container
homepage: https://www.github.com/kranfix/dart-circularbuffer
documentation: https://www.github.com/kranfix/dart-circularbuffer#readme
environment:
  sdk: ">=2.10.0 <3.0.0"
