name: circular_buffer
version: 0.7.0
description: A Dart Circular Buffer container
homepage: http://www.github.com/kranfix/dart-circularbuffer
documentation: http://www.github.com/kranfix/dart-circularbuffer#readme
environment:
  sdk: ">=2.1.0 <3.0.0"
