name: circular_buffer
version: 0.12.0
description: >
  A Dart Circular Buffer container based on List with a fixed capacity.
homepage: https://www.github.com/kranfix/dart-circularbuffer
documentation: https://www.github.com/kranfix/dart-circularbuffer#readme
environment:
  sdk: ">=2.13.0 <=4.0.0"

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^6.0.0
